gyg_app_homepage:
    path:     /hello/{name}
    defaults: { _controller: GYGAppBundle:Default:index }

gyg_app_adminpage:
    path:     /admin
    defaults: { _controller: GYGAppBundle:Default:admin }

gyg_app_api_test:
    path:   /api/test
    defaults:  { _controller: GYGAppBundle:Api:test }

gyg_app_api_location:
    path:   /api/trajet/{location}
    defaults:  { _controller: GYGAppBundle:Api:getLocation }




gyg_app_list_point_apport:
    path: /admin/list-point-apport
    defaults: { _controller: GYGAppBundle:PointApport:list }

gyg_app_delete_point_apport:
    path: /admin/delete-point-apport/{idPointApport}
    defaults: { _controller: GYGAppBundle:PointApport:delete }
    requirements:
        idPointApport:  \d+

gyg_app_edit_point_apport:
    path: /admin/edit-point-apport/{idPointApport}
    defaults: { _controller: GYGAppBundle:PointApport:edit, idPointApport: 0 }
    requirements:
        idPointApport:  \d+





gyg_app_list_decheterie:
    path: /admin/list-decheterie
    defaults: { _controller: GYGAppBundle:Decheterie:list }

gyg_app_delete_decheterie:
    path: /admin/delete-decheterie/{idDecheterie}
    defaults: { _controller: GYGAppBundle:Decheterie:delete }
    requirements:
        idDecheterie:  \d+

gyg_app_edit_decheterie:
    path: /admin/edit-decheterie/{idDecheterie}
    defaults: { _controller: GYGAppBundle:Decheterie:edit, idDecheterie: 0 }
    requirements:
        idDecheterie:  \d+