gyg_app_homepage:
    path:     /hello/{name}
    defaults: { _controller: GYGAppBundle:Default:index }

gyg_app_adminpage:
    path:     /admin
    defaults: { _controller: GYGAppBundle:Default:admin }

gyg_app_add_point_apport:
  path: /admin/add-point-apport
  defaults: { _controller: GYGAppBundle:PointApport:add }

gyg_app_list_point_apport:
  path: /
  defaults: { _controller: GYGAppBundle:PointApport:list }

gyg_app_api_test:
    path:   /api/test
    defaults:  { _controller: GYGAppBundle:Api:test }

gyg_app_api_point_apport:
    path:   /api/point-apport
    defaults:  { _controller: GYGAppBundle:Api:getPointApport }

gyg_app_api_trajet:
    path:   /api/trajet
    defaults:  { _controller: GYGAppBundle:Api:getTrajet }

gyg_app_delete_point_apport:
  path: /admin/delete-point-apport/{idPointApport}
  defaults: { _controller: GYGAppBundle:PointApport:delete }
  requirements:
          idPointApport:  \d+
