gyg_app_homepage:
    path:     /hello/{name}
    defaults: { _controller: GYGAppBundle:Default:index }

gyg_app_adminpage:
    path:     /admin
    defaults: { _controller: GYGAppBundle:Default:admin }

gyg_app_add_point_apport_aerien:
  path: /add_point_apport_aerien
  defaults: { _controller: GYGAppBundle:PointApportAerien:add }

gyg_app_add_point_apport_enterre:
  path: /add_point_apport_enterre
  defaults: { _controller: GYGAppBundle:PointApportEnterre:add }

gyg_app_api_test:
    path:   /api/test
    defaults:  { _controller: GYGAppBundle:Api:test }

gyg_app_api_point_apport:
    path:   /api/point-apport
    defaults:  { _controller: GYGAppBundle:Api:getPointApport }
