gyg_app_homepage:
    path:     /
    defaults: { _controller: GYGAppBundle:Default:index }

gyg_app_adminpage:
    path:     /admin
    defaults: { _controller: GYGAppBundle:Default:admin }

gyg_app_api_test:
    path:   /api/test
    defaults:  { _controller: GYGAppBundle:Api:test }

gyg_app_api_point_apport:
    path:   /api/point-apport
    defaults:  { _controller: GYGAppBundle:Api:getPointApport }

gyg_app_api_trajet:
    path:   /api/trajet
    defaults:  { _controller: GYGAppBundle:Api:getTrajet }

gyg_app_api_dechetterie:
    path:   /api/dechetterie
    defaults:  { _controller: GYGAppBundle:Api:getDechetterie }

gyg_app_api_dechet_soin:
    path:   /api/dechet-soin
    defaults:  { _controller: GYGAppBundle:Api:getDechetSoin }

gyg_app_api_textile:
    path:   /api/textile
    defaults:  { _controller: GYGAppBundle:Api:getTextile }

gyg_app_delete_point_apport:
    path: /admin/delete-point-apport/{idPointApport}
    defaults: { _controller: GYGAppBundle:PointApport:delete }
    requirements:
        idPointApport:  \d+

gyg_app_edit_point_apport:
    path: /admin/edit-point-apport/{idPointApport}
    defaults: { _controller: GYGAppBundle:PointApport:edit, idPointApport: 0 }
    requirements:
        idPointApport:  \d+

gyg_app_delete_decheterie:
    path: /admin/delete-decheterie/{idDecheterie}
    defaults: { _controller: GYGAppBundle:Decheterie:delete }
    requirements:
        idDecheterie:  \d+

gyg_app_edit_decheterie:
    path: /admin/edit-decheterie/{idDecheterie}
    defaults: { _controller: GYGAppBundle:Decheterie:edit, idDecheterie: 0 }
    requirements:
        idDecheterie:  \d+

gyg_app_delete_textile:
    path: /admin/delete-textile/{idTextile}
    defaults: { _controller: GYGAppBundle:Textile:delete }
    requirements:
        idTextile:  \d+

gyg_app_edit_textile:
    path: /admin/edit-textile/{idTextile}
    defaults: { _controller: GYGAppBundle:Textile:edit, idTextile: 0 }
    requirements:
        idTextile:  \d+

gyg_app_delete_dechet_soin:
    path: /admin/delete-dechet-soin/{idDechetSoin}
    defaults: { _controller: GYGAppBundle:DechetSoin:delete }
    requirements:
        idDechetSoin:  \d+

gyg_app_edit_dechet_soin:
    path: /admin/edit-dechet-soin/{idDechetSoin}
    defaults: { _controller: GYGAppBundle:DechetSoin:edit, idDechetSoin: 0 }
    requirements:
        idDechetSoin:  \d+

gyg_app_delete_trajet:
    path: /admin/delete-trajet/{idTrajet}
    defaults: { _controller: GYGAppBundle:Trajet:delete }
    requirements:
        idTrajet:  \d+

gyg_app_edit_trajet:
    path: /admin/edit-trajet/{idTrajet}
    defaults: { _controller: GYGAppBundle:Trajet:edit, idTrajet: 0 }
    requirements:
        idTrajet:  \d+
