services:
#    gyg_app.example:
#        class: GYG\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  hydrator_point_apport:
    class:        GYG\AppBundle\Hydrator\PointApportHydrator
    arguments:    [@service_geo_json]
  hydrator_trajet:
    class:        GYG\AppBundle\Hydrator\TrajetHydrator
    arguments:    [@service_geo_json]
  hydrator_dechet_soin:
      class:        GYG\AppBundle\Hydrator\DechetSoinHydrator
      arguments:    [@service_geo_json]
  service_geo_json:
    class:        GYG\AppBundle\Service\GeoJson
