gyg_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: GYGUserBundle:Default:index }

gyg_user_delete:
    path:     /admin/delete-user/{idUser}
    defaults: { _controller: GYGUserBundle:User:delete }
    requirements:
        idDecheterie:  \d+

gyg_user_list:
    path:     /admin/list-users
    defaults: { _controller: GYGUserBundle:User:list }